/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface NewOrderData {
  'destination' : string,
  'paymentMethod' : PaymentMethod,
  'university' : string,
  'pincode' : number,
  'itemIds' : Uint32Array,
}
export interface OrderData {
  'id' : bigint,
  'destination' : string,
  'paymentMethod' : PaymentMethod,
  'user' : Principal,
  'university' : string,
  'timestamp' : bigint,
  'pincode' : number,
  'itemIds' : Uint32Array,
}
export type PaymentMethod = { 'cashOnDelivery' : null } |
  { 'online' : null };
export interface Product {
  'id' : number,
  'retailPrice' : number,
  'name' : string,
  'origin' : string,
  'category' : string,
}
export interface RoundInfo { 'closingDate' : string, 'roundNumber' : number }
export interface RoundInfoArgs {
  'closingDate' : string,
  'roundNumber' : number,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addProduct' : ActorMethod<[string, number, string, string], number>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getAllOrders' : ActorMethod<[], Array<OrderData>>,
  'getAllOrdersByTimestamp' : ActorMethod<[], Array<OrderData>>,
  'getAllProducts' : ActorMethod<[], Array<Product>>,
  'getAllProductsByName' : ActorMethod<[], Array<Product>>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCurrentRoundInfo' : ActorMethod<[], RoundInfo>,
  'getMyOrders' : ActorMethod<[], Array<OrderData>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'placeOrder' : ActorMethod<[NewOrderData], bigint>,
  'removeProduct' : ActorMethod<[number], undefined>,
  'setCurrentRoundInfo' : ActorMethod<[RoundInfoArgs], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];