/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface NewOrderData {
  'destination' : string,
  'paymentMethod' : PaymentMethod,
  'university' : string,
  'pincode' : number,
  'itemIds' : Uint32Array,
}
export interface OrderDataWithStatus {
  'id' : bigint,
  'status' : OrderStatus,
  'destination' : string,
  'paymentMethod' : PaymentMethod,
  'user' : Principal,
  'university' : string,
  'timestamp' : bigint,
  'pincode' : number,
  'itemIds' : Uint32Array,
}
export type OrderStatus = { 'shipped' : null } |
  { 'paymentConfirmed' : null } |
  { 'pendingPayment' : null } |
  { 'receivedByUser' : null } |
  { 'delivered' : null };
export type PaymentMethod = { 'cashOnDelivery' : null } |
  { 'online' : null };
export interface PaynowConfig {
  'returnUrl' : string,
  'integrationId' : string,
  'resultUrl' : string,
  'integrationKey' : string,
}
export interface Product {
  'id' : number,
  'retailPrice' : number,
  'name' : string,
  'origin' : string,
  'category' : string,
}
export interface RoundInfo { 'closingDate' : string, 'roundNumber' : number }
export interface RoundInfoArgs {
  'closingDate' : string,
  'roundNumber' : number,
}
export interface UserProfile {
  'name' : string,
  'email' : string,
  'phone' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addProduct' : ActorMethod<[string, string, number, string, string], number>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'changeAdminPassword' : ActorMethod<[string, string], boolean>,
  'checkAdminPassword' : ActorMethod<[string], boolean>,
  'confirmOrderReceived' : ActorMethod<[bigint], undefined>,
  'getAllOrders' : ActorMethod<[string], Array<OrderDataWithStatus>>,
  'getAllProducts' : ActorMethod<[], Array<Product>>,
  'getAllProductsByName' : ActorMethod<[], Array<Product>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCurrentRoundInfo' : ActorMethod<[], RoundInfo>,
  'getMyOrders' : ActorMethod<[], Array<OrderDataWithStatus>>,
  'getPaynowConfig' : ActorMethod<[string], PaynowConfig>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'placeOrder' : ActorMethod<[NewOrderData], bigint>,
  'removeProduct' : ActorMethod<[string, number], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setCurrentRoundInfo' : ActorMethod<[string, RoundInfoArgs], undefined>,
  'setPaynowConfig' : ActorMethod<[string, PaynowConfig], undefined>,
  'updateOrderStatus' : ActorMethod<[string, bigint, OrderStatus], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];